/*
 * reldex.h — the stable C ABI between the C++/Qt adapter and the Reldex core.
 *
 * GENERATED by cbindgen from crates/ffi. Do not edit by hand: run
 * crates/ffi/gen-header.sh and commit the result. CI fails on a stale copy.
 *
 * Contract summary (the full rules are in the Rust doc comments below and in
 * docs/decisions/0003-qt-rust-integration.md):
 *
 *   - Check reldex_abi_version() against RELDEX_ABI_VERSION before anything
 *     else; refuse to start on a major mismatch.
 *   - Every non-opaque struct starts with uint32_t struct_size. Set it to
 *     sizeof(the struct) before every call, in and out.
 *   - Every enum reserves 0 for a value this header predates. Treat an
 *     unknown value as unknown; never assert on it.
 *   - All calls except reldex_session_request_cancel come from one thread.
 *   - The waker must not block and must not call back into reldex_*.
 *   - A ReldexBatch* and a ReldexError* handed out by an event are YOURS:
 *     release them with reldex_batch_release / reldex_error_free.
 */


#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Major part of the ABI version reported by [`reldex_abi_version`].
 *
 * Bumped when an existing symbol's meaning, an existing struct field's
 * meaning, or an existing enum value changes. The adapter refuses to start on
 * a mismatch (ADR-0003 D7).
 */
#define RELDEX_ABI_VERSION_MAJOR 1

/**
 * Minor part of the ABI version reported by [`reldex_abi_version`].
 *
 * Bumped when a symbol, a *trailing* struct field, or an enum value is added.
 * An older adapter keeps working: every non-opaque struct starts with
 * `struct_size`, and every enum reserves `0` for "a value this header
 * predates".
 */
#define RELDEX_ABI_VERSION_MINOR 0

/**
 * How many significant digits a [`ReldexNumber`] carries.
 *
 * Written as a literal so the generated header can use it as an array bound;
 * the assertion below keeps it equal to the contract's own constant, so the
 * two can never drift (ADR-0002 amendment S6 raised it from 38 to 40).
 */
#define RELDEX_NUMBER_MAX_DIGITS 40



/**
 * What an exported function reports.
 *
 * `0` is reserved for "a status this header predates", per ADR-0003 D7: an
 * adapter must treat an unmapped value as an unknown failure rather than
 * assert.
 */
enum ReldexStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A status value this header does not know. Never returned by this
   * library; reserved so an older adapter can recognise a newer one.
   */
  RELDEX_STATUS_UNKNOWN = 0,
  /**
   * The call succeeded.
   */
  RELDEX_STATUS_OK = 1,
  /**
   * The call failed with a database or core error. Take the details with
   * [`crate::reldex_last_error_take`].
   */
  RELDEX_STATUS_ERROR = 2,
  /**
   * An argument was null, unaligned, out of range, or carried a
   * `struct_size` this build cannot honour. Nothing was done.
   */
  RELDEX_STATUS_INVALID_ARGUMENT = 3,
  /**
   * The object is not in a state where this call makes sense — a session
   * that is still opening, or one that is closed.
   */
  RELDEX_STATUS_INVALID_STATE = 4,
  /**
   * An id was not found: it belongs to another session, or it was already
   * closed. Reported, never undefined behaviour (ADR-0003 D3).
   */
  RELDEX_STATUS_NOT_FOUND = 5,
  /**
   * A panic was caught at the boundary. The process is intact and the call
   * did nothing useful; the panic message is in the thread-local last
   * error. This is a bug in Reldex, not an expected outcome.
   */
  RELDEX_STATUS_PANIC = 6,
  /**
   * The call was made from inside a waker callback, which the D5 contract
   * forbids. Nothing was done — the alternative is a deadlock.
   */
  RELDEX_STATUS_REENTRANT = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexStatus ReldexStatus;
#else
typedef int32_t ReldexStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Why an operation failed, as a vendor-neutral category.
 *
 * `ErrorKind` is `#[non_exhaustive]` in Rust, so `0` is reserved here for a
 * kind this header predates: an adapter must map an unknown value to
 * "unknown" rather than assert (ADR-0003 D6). The native code in
 * [`ReldexErrorView::native_code`] carries the vendor's own classification
 * regardless.
 */
enum ReldexErrorKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A kind this header does not know.
   */
  RELDEX_ERROR_KIND_UNKNOWN = 0,
  /**
   * Connection parameters are invalid or incomplete; nothing was attempted.
   */
  RELDEX_ERROR_KIND_CONFIGURATION = 1,
  /**
   * A connection could not be established.
   */
  RELDEX_ERROR_KIND_CONNECTION = 2,
  /**
   * The server rejected the credentials or the authentication method.
   */
  RELDEX_ERROR_KIND_AUTHENTICATION = 3,
  /**
   * An established connection was lost mid-operation.
   */
  RELDEX_ERROR_KIND_NETWORK_LOST = 4,
  /**
   * An operation exceeded a configured time limit.
   */
  RELDEX_ERROR_KIND_TIMEOUT = 5,
  /**
   * The operation was cancelled.
   */
  RELDEX_ERROR_KIND_CANCELLED = 6,
  /**
   * The statement could not be parsed or compiled.
   */
  RELDEX_ERROR_KIND_SYNTAX = 7,
  /**
   * A database constraint was violated.
   */
  RELDEX_ERROR_KIND_CONSTRAINT = 8,
  /**
   * The session lacks privileges for the object or operation.
   */
  RELDEX_ERROR_KIND_PERMISSION = 9,
  /**
   * The operation failed because of transaction state.
   */
  RELDEX_ERROR_KIND_TRANSACTION = 10,
  /**
   * A server-side or client-side resource limit was reached.
   */
  RELDEX_ERROR_KIND_RESOURCE = 11,
  /**
   * A value could not be represented without loss, or was not valid for its
   * declared type.
   */
  RELDEX_ERROR_KIND_DATA_CONVERSION = 12,
  /**
   * The driver does not implement the requested capability.
   */
  RELDEX_ERROR_KIND_UNSUPPORTED = 13,
  /**
   * A Reldex or driver bug. An invalid FFI argument is reported as this.
   */
  RELDEX_ERROR_KIND_DRIVER_INTERNAL = 14,
  /**
   * A database-reported error the driver could not classify.
   */
  RELDEX_ERROR_KIND_OTHER = 15,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexErrorKind ReldexErrorKind;
#else
typedef int32_t ReldexErrorKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What the driver believes about the session after a failure, plus the two
 * core-side terminal states.
 *
 * `0` is reserved as unknown for the same reason as
 * [`ReldexErrorKind::Unknown`].
 */
enum ReldexSessionState
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A state this header does not know.
   */
  RELDEX_SESSION_STATE_UNKNOWN = 0,
  /**
   * The session is known to be usable; the failure was confined to the call.
   */
  RELDEX_SESSION_STATE_USABLE = 1,
  /**
   * The session may be usable; it will be validated before the next request.
   */
  RELDEX_SESSION_STATE_NEEDS_VALIDATION = 2,
  /**
   * The session is gone. Any transaction it held is lost.
   */
  RELDEX_SESSION_STATE_LOST = 3,
  /**
   * The session was closed by the caller.
   */
  RELDEX_SESSION_STATE_CLOSED = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexSessionState ReldexSessionState;
#else
typedef int32_t ReldexSessionState;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which request an event is the reply to.
 *
 * `0` is reserved for a kind this header predates (ADR-0003 D7). Exactly one
 * event is delivered per accepted request; an event whose `error` is non-null
 * is that request's *failure*, still delivered under its own kind so the
 * adapter never has to guess which operation failed.
 */
enum ReldexEventKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A kind this header does not know.
   */
  RELDEX_EVENT_KIND_UNKNOWN = 0,
  /**
   * Reply to `reldex_hub_open_session`.
   */
  RELDEX_EVENT_KIND_OPENED = 1,
  /**
   * Reply to `reldex_session_execute`.
   */
  RELDEX_EVENT_KIND_EXECUTED = 2,
  /**
   * Reply to `reldex_session_fetch`. On success `batch` is non-null and the
   * caller owns it.
   */
  RELDEX_EVENT_KIND_FETCHED = 3,
  /**
   * Reply to `reldex_session_close_result`.
   */
  RELDEX_EVENT_KIND_RESULT_CLOSED = 4,
  /**
   * Reply to `reldex_session_close`. Read `close_outcome`: a close can fail
   * and leave the session **open**.
   */
  RELDEX_EVENT_KIND_SESSION_CLOSED = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexEventKind ReldexEventKind;
#else
typedef int32_t ReldexEventKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What kind of statement the server ran, as far as the driver could tell.
 *
 * `0` is reserved for a kind this header predates.
 */
enum ReldexStatementKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A kind this header does not know.
   */
  RELDEX_STATEMENT_KIND_UNKNOWN = 0,
  /**
   * A query that returns rows.
   */
  RELDEX_STATEMENT_KIND_QUERY = 1,
  /**
   * Data manipulation.
   */
  RELDEX_STATEMENT_KIND_DML = 2,
  /**
   * Data definition — note `committed_implicitly`.
   */
  RELDEX_STATEMENT_KIND_DDL = 3,
  /**
   * An anonymous PL/SQL block or a call into stored code.
   */
  RELDEX_STATEMENT_KIND_PL_SQL_BLOCK = 4,
  /**
   * Transaction control submitted as text.
   */
  RELDEX_STATEMENT_KIND_TRANSACTION_CONTROL = 5,
  /**
   * Session control (`ALTER SESSION` and similar).
   */
  RELDEX_STATEMENT_KIND_SESSION_CONTROL = 6,
  /**
   * Something else, or the driver could not classify it.
   */
  RELDEX_STATEMENT_KIND_OTHER = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexStatementKind ReldexStatementKind;
#else
typedef int32_t ReldexStatementKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * How a session close ended.
 *
 * Three of these leave the session **open and usable**, so the adapter can
 * ask the user and try again; only `CLOSED` and `FAILED` end the session
 * (`SPEC.md` §10 — Reldex never silently commits, and never hides a
 * transaction it could not resolve).
 */
enum ReldexCloseOutcome
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * An outcome this header does not know.
   */
  RELDEX_CLOSE_OUTCOME_UNKNOWN = 0,
  /**
   * The session is closed.
   */
  RELDEX_CLOSE_OUTCOME_CLOSED = 1,
  /**
   * A transaction may be open and no disposition was given. **Still open.**
   */
  RELDEX_CLOSE_OUTCOME_DECISION_REQUIRED = 2,
  /**
   * The requested commit failed, so the transaction is unchanged.
   * **Still open.**
   */
  RELDEX_CLOSE_OUTCOME_COMMIT_FAILED = 3,
  /**
   * The requested rollback failed, so the transaction is unchanged.
   * **Still open.**
   */
  RELDEX_CLOSE_OUTCOME_ROLLBACK_FAILED = 4,
  /**
   * The transaction was resolved (or there was none) but closing failed, or
   * the session was already lost — in which case nothing was committed. The
   * session is closed either way and must not be reused.
   */
  RELDEX_CLOSE_OUTCOME_FAILED = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexCloseOutcome ReldexCloseOutcome;
#else
typedef int32_t ReldexCloseOutcome;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The storage family of a column, which decides which fields of
 * [`ReldexColumnView`] are set.
 *
 * `0` is reserved for a kind this header predates (ADR-0003 D7).
 */
enum ReldexColumnKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A kind this header does not know. Read such a column through
   * [`crate::reldex_batch_format_column`], which always has an answer.
   */
  RELDEX_COLUMN_KIND_UNKNOWN = 0,
  /**
   * `bool`: `fixed` is a `bool[]`.
   */
  RELDEX_COLUMN_KIND_BOOLEAN = 1,
  /**
   * Exact decimals: `fixed` is a [`ReldexNumber`] array.
   */
  RELDEX_COLUMN_KIND_NUMBER = 2,
  /**
   * `fixed` is a `float[]`.
   */
  RELDEX_COLUMN_KIND_FLOAT = 3,
  /**
   * `fixed` is a `double[]`.
   */
  RELDEX_COLUMN_KIND_DOUBLE = 4,
  /**
   * UTF-8 text: `data` + `offsets`, borrowed.
   */
  RELDEX_COLUMN_KIND_TEXT = 5,
  /**
   * Raw bytes: `data` + `offsets`, borrowed.
   */
  RELDEX_COLUMN_KIND_BYTES = 6,
  /**
   * Dates and timestamps: `fixed` is a [`ReldexTimestamp`] array.
   */
  RELDEX_COLUMN_KIND_TIMESTAMP = 7,
  /**
   * JSON text: `data` + `offsets`, borrowed.
   */
  RELDEX_COLUMN_KIND_JSON = 8,
  /**
   * An unread large object. No data crosses: the locator stays on the
   * session's worker thread and a non-NULL row reads as *taken*, which is
   * not NULL and must not be shown as one. Reading LOBs is M2.11.
   */
  RELDEX_COLUMN_KIND_LOB = 9,
  /**
   * A type the contract cannot represent, rendered by the driver as
   * best-effort text: `data` + `offsets`, borrowed. Not text — never show
   * it as character data.
   */
  RELDEX_COLUMN_KIND_UNSUPPORTED = 10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexColumnKind ReldexColumnKind;
#else
typedef int32_t ReldexColumnKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Whether a column accepts NULLs, when the server said.
 */
enum ReldexNullable
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * The driver did not report it. Not the same as "NOT NULL".
   */
  RELDEX_NULLABLE_UNKNOWN = 0,
  /**
   * The column accepts NULLs.
   */
  RELDEX_NULLABLE_YES = 1,
  /**
   * The column does not.
   */
  RELDEX_NULLABLE_NO = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexNullable ReldexNullable;
#else
typedef int32_t ReldexNullable;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * How a timestamp is rendered.
 */
enum ReldexTimestampStyle
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A style this header does not know; treated as `ISO_8601`.
   */
  RELDEX_TIMESTAMP_STYLE_UNKNOWN = 0,
  /**
   * `2026-01-02T13:45:30.123456789+07:00`, with the fractional part and the
   * zone present only when the value has them.
   */
  RELDEX_TIMESTAMP_STYLE_ISO8601 = 1,
  /**
   * The same, with a space instead of the `T`.
   */
  RELDEX_TIMESTAMP_STYLE_ISO8601_SPACE = 2,
  /**
   * `2026-01-02`: the date only.
   */
  RELDEX_TIMESTAMP_STYLE_DATE_ONLY = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexTimestampStyle ReldexTimestampStyle;
#else
typedef int32_t ReldexTimestampStyle;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * How raw bytes are rendered.
 */
enum ReldexBytesStyle
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A style this header does not know; treated as `HEX_UPPER`.
   */
  RELDEX_BYTES_STYLE_UNKNOWN = 0,
  /**
   * `0A1B2C`.
   */
  RELDEX_BYTES_STYLE_HEX_UPPER = 1,
  /**
   * `0a1b2c`.
   */
  RELDEX_BYTES_STYLE_HEX_LOWER = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexBytesStyle ReldexBytesStyle;
#else
typedef int32_t ReldexBytesStyle;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a cancel on this session can actually do (`SPEC.md` §24.8).
 *
 * `0` is reserved for a kind this header predates.
 */
enum ReldexCancelKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A kind this header does not know.
   */
  RELDEX_CANCEL_KIND_UNKNOWN = 0,
  /**
   * The driver cannot stop a running statement at all. The UI must not
   * offer Cancel.
   */
  RELDEX_CANCEL_KIND_UNSUPPORTED = 1,
  /**
   * The driver can only enforce a deadline armed *before* the statement
   * started. The UI must say when the statement will stop, not pretend a
   * cancel is in flight.
   */
  RELDEX_CANCEL_KIND_PRE_ARMED_DEADLINE = 2,
  /**
   * The driver can interrupt a running statement.
   */
  RELDEX_CANCEL_KIND_NATIVE = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexCancelKind ReldexCancelKind;
#else
typedef int32_t ReldexCancelKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a cancel request achieved.
 *
 * `0` is reserved for an outcome this header predates.
 */
enum ReldexCancelOutcome
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * An outcome this header does not know.
   */
  RELDEX_CANCEL_OUTCOME_UNKNOWN = 0,
  /**
   * An interrupt was delivered or armed. Best effort: the statement may
   * still finish normally, and its outcome arrives as its own event.
   */
  RELDEX_CANCEL_OUTCOME_REQUESTED = 1,
  /**
   * Nothing was sent and nothing will stop early — this driver cannot
   * interrupt a running call. The UI must not show a cancel in progress.
   */
  RELDEX_CANCEL_OUTCOME_NOT_INTERRUPTIBLE = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexCancelOutcome ReldexCancelOutcome;
#else
typedef int32_t ReldexCancelOutcome;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What to do with a possibly-open transaction when closing a session.
 *
 * `RELDEX_CLOSE_DISPOSITION_NONE` is the honest default: if a transaction may
 * be open, the close comes back as
 * `RELDEX_CLOSE_OUTCOME_DECISION_REQUIRED` with the session still open, so
 * the user can be asked. Reldex never silently commits (`SPEC.md` §10).
 */
enum ReldexCloseDisposition
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A disposition this header does not know.
   */
  RELDEX_CLOSE_DISPOSITION_UNKNOWN = 0,
  /**
   * No decision has been made yet.
   */
  RELDEX_CLOSE_DISPOSITION_NONE = 1,
  /**
   * Commit the open transaction before closing.
   */
  RELDEX_CLOSE_DISPOSITION_COMMIT = 2,
  /**
   * Roll the open transaction back before closing.
   */
  RELDEX_CLOSE_DISPOSITION_ROLLBACK = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexCloseDisposition ReldexCloseDisposition;
#else
typedef int32_t ReldexCloseDisposition;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which driver a session is opened against.
 *
 * `0` is reserved for a kind this header predates (ADR-0003 D7).
 */
enum ReldexDriverKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A driver this header does not know, or none requested.
   */
  RELDEX_DRIVER_KIND_UNKNOWN = 0,
  /**
   * The in-process mock driver: no database, deterministic, and the only
   * driver a build with the `mock-driver` feature can open.
   */
  RELDEX_DRIVER_KIND_MOCK = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexDriverKind ReldexDriverKind;
#else
typedef int32_t ReldexDriverKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which scripted world a mock session connects to.
 */
enum ReldexMockScenario
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A scenario this header does not know.
   */
  RELDEX_MOCK_SCENARIO_UNKNOWN = 0,
  /**
   * The spike S14/S15 world. Its statements are listed in
   * [`ReldexMockStatement`]: a lazily generated result of the S14 shape
   * (`ID NUMBER`, `NAME VARCHAR2(40)` including NULL, Thai and non-BMP
   * rows, `CREATED DATE`), a statement that blocks, one that fails with a
   * native code and a position, and one that panics inside the driver.
   */
  RELDEX_MOCK_SCENARIO_S14 = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexMockScenario ReldexMockScenario;
#else
typedef int32_t ReldexMockScenario;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A statement the [`ReldexMockScenario::S14`] world answers.
 */
enum ReldexMockStatement
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A statement this header does not know.
   */
  RELDEX_MOCK_STATEMENT_UNKNOWN = 0,
  /**
   * The generated result: `rows` rows of the S14 shape.
   */
  RELDEX_MOCK_STATEMENT_GENERATED_QUERY = 1,
  /**
   * Blocks the session's worker until released — by
   * [`reldex_mock_release_block`], by the configured duration elapsing, or
   * by a cancel.
   */
  RELDEX_MOCK_STATEMENT_BLOCK = 2,
  /**
   * Fails with `ORA-00942` at line 1, column 15.
   */
  RELDEX_MOCK_STATEMENT_FAILING = 3,
  /**
   * Panics inside the driver call. `db-core` contains the panic and reports
   * it as an error; nothing aborts (ADR-0002 K6).
   */
  RELDEX_MOCK_STATEMENT_PANICKING = 4,
  /**
   * One row of DML, which opens a transaction — so a later close with no
   * disposition must come back as `DECISION_REQUIRED` rather than
   * committing anything (`SPEC.md` §10).
   */
  RELDEX_MOCK_STATEMENT_DML = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReldexMockStatement ReldexMockStatement;
#else
typedef int32_t ReldexMockStatement;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * One fetched batch, owned by the caller from the moment its event is handed
 * out until [`reldex_batch_release`].
 *
 * Opaque. Every pointer any function here returns borrows from it.
 */
typedef struct ReldexBatch ReldexBatch;

/**
 * One failure, owned by the caller from the moment it is handed out.
 *
 * Opaque: read it with [`reldex_error_view`], release it with
 * [`reldex_error_free`]. Every string in the view borrows from this object
 * and dies with it.
 */
typedef struct ReldexError ReldexError;

/**
 * The application hub: one event queue, one waker, one session registry.
 *
 * Opaque to C. Create it with [`reldex_hub_create`] and release it with
 * [`reldex_hub_destroy`], last of all.
 */
typedef struct ReldexHub ReldexHub;

/**
 * Somewhere for formatted text to land: one buffer plus offsets, reusable.
 *
 * Opaque. Create one per grid (not per call), [`reldex_text_arena_clear`] it
 * before each window, and release it with [`reldex_text_arena_release`].
 */
typedef struct ReldexTextArena ReldexTextArena;

/**
 * A borrowed UTF-8 string: pointer plus length in **bytes**.
 *
 * Always NUL-terminated at `ptr[len]` as a convenience for C, but `len` is
 * authoritative — a string that contains a NUL byte is still `len` bytes
 * long. Never owned by the caller: it borrows from whatever produced it (an
 * error, a batch, an arena) and dies with it.
 */
typedef struct ReldexStr {
  /**
   * First byte. Never null: an empty string points at a NUL byte.
   */
  const uint8_t *ptr;
  /**
   * Length in bytes, excluding the trailing NUL.
   */
  size_t len;
} ReldexStr;

/**
 * What a column *is*, as opposed to how it is stored: the header a grid puts
 * above it.
 *
 * `name` and `native_type_name` borrow from the batch.
 */
typedef struct ReldexColumnInfo {
  /**
   * `sizeof(ReldexColumnInfo)` on the way in; how much is valid on the way
   * out.
   */
  uint32_t struct_size;
  /**
   * A [`ReldexColumnKind`] — how the batch stores this column.
   */
  int32_t kind;
  /**
   * A [`ReldexNullable`].
   */
  int32_t nullable;
  /**
   * Declared precision, when `has_precision`.
   */
  int32_t precision;
  /**
   * Declared scale, when `has_scale`. May be negative.
   */
  int32_t scale;
  /**
   * Declared maximum size in bytes, when `has_max_size_bytes`.
   */
  uint32_t max_size_bytes;
  /**
   * Whether `precision` is set.
   */
  bool has_precision;
  /**
   * Whether `scale` is set.
   */
  bool has_scale;
  /**
   * Whether `max_size_bytes` is set.
   */
  bool has_max_size_bytes;
  /**
   * The column's name, as the server gave it.
   */
  struct ReldexStr name;
  /**
   * The server's own type name, when the driver reported one — required
   * reading for an `Unsupported` column, which is where the real type hides.
   */
  struct ReldexStr native_type_name;
} ReldexColumnInfo;

/**
 * What one column of a batch looks like in memory.
 *
 * Every pointer here **borrows from the batch** and is valid until
 * [`reldex_batch_release`]. Which pointers are set depends on `kind`; see
 * [`ReldexColumnKind`].
 */
typedef struct ReldexColumnView {
  /**
   * `sizeof(ReldexColumnView)` on the way in; how much is valid on the way
   * out.
   */
  uint32_t struct_size;
  /**
   * A [`ReldexColumnKind`].
   */
  int32_t kind;
  /**
   * How many rows the column holds. The same for every column of a batch.
   */
  size_t row_count;
  /**
   * The NULL bitmap: row `i` is bit `i % 64` of word `i / 64`, LSB-first,
   * set when the row is SQL NULL. Null only when `null_word_count` is 0.
   */
  const uint64_t *null_bits;
  /**
   * How many `uint64_t` words `null_bits` covers.
   */
  size_t null_word_count;
  /**
   * Text/JSON/bytes/unsupported: the one contiguous value buffer.
   */
  const uint8_t *data;
  /**
   * How many bytes `data` covers.
   */
  size_t data_len;
  /**
   * Text/JSON/bytes/unsupported: `row_count + 1` byte offsets into `data`,
   * so row `i` is `data[offsets[i]..offsets[i + 1]]`.
   */
  const size_t *offsets;
  /**
   * Fixed-width kinds: the element array.
   */
  const void *fixed;
  /**
   * The size of one element of `fixed`. Compare with `sizeof` of the
   * matching type before reading.
   */
  size_t fixed_stride;
  /**
   * How many elements `fixed` covers; equals `row_count`.
   */
  size_t fixed_len;
} ReldexColumnView;

/**
 * A read-only description of a [`ReldexError`], with every string borrowed
 * from it.
 *
 * The caller sets `struct_size` before the call; see
 * [`crate::reldex_error_view`].
 */
typedef struct ReldexErrorView {
  /**
   * `sizeof(ReldexErrorView)` on the way in; how much of it is valid on the
   * way out.
   */
  uint32_t struct_size;
  /**
   * A [`ReldexErrorKind`].
   */
  int32_t kind;
  /**
   * A [`ReldexSessionState`].
   */
  int32_t session_state;
  /**
   * The vendor's numeric code (`ORA-00942` is `942`), when `has_native`.
   */
  int32_t native_code;
  /**
   * Position in the statement text, counted in Unicode **scalars**, when
   * `has_char_offset`. Convert with [`crate::reldex_utf16_offset`].
   */
  uint32_t char_offset;
  /**
   * 1-based line, when `has_line_column`.
   */
  uint32_t line;
  /**
   * 1-based column, when `has_line_column`.
   */
  uint32_t column;
  /**
   * Whether retrying the same operation could plausibly succeed.
   */
  bool retryable;
  /**
   * Whether `native_code` and `native_message` carry a vendor error.
   */
  bool has_native;
  /**
   * Whether `char_offset` is set.
   */
  bool has_char_offset;
  /**
   * Whether `line` and `column` are set.
   */
  bool has_line_column;
  /**
   * Reldex's own message.
   */
  struct ReldexStr message;
  /**
   * The vendor's own message, unmodified; empty when `!has_native`.
   */
  struct ReldexStr native_message;
  /**
   * The rendered `source` chain, or empty.
   */
  struct ReldexStr cause;
} ReldexErrorView;

/**
 * What an arena holds: the same buffer-plus-offsets shape a text column has.
 *
 * Both pointers borrow from the arena and are invalidated by the next
 * [`reldex_batch_format_column`], [`reldex_text_arena_clear`] or
 * [`reldex_text_arena_release`] on it.
 */
typedef struct ReldexArenaView {
  /**
   * `sizeof(ReldexArenaView)` on the way in; how much is valid on the way
   * out.
   */
  uint32_t struct_size;
  /**
   * The one contiguous UTF-8 buffer.
   */
  const uint8_t *data;
  /**
   * How many bytes `data` covers.
   */
  size_t data_len;
  /**
   * `count + 1` byte offsets: string `i` is `data[offsets[i]..offsets[i+1]]`.
   */
  const size_t *offsets;
  /**
   * How many strings the arena holds.
   */
  size_t count;
} ReldexArenaView;

/**
 * The user's formatting settings, passed in per call.
 *
 * Every field is optional in the ADR-0003 D7 sense: zero means the documented
 * default, so `NULL` options (or a zeroed struct with only `struct_size` set)
 * give sensible output.
 */
typedef struct ReldexFormatOptions {
  /**
   * `sizeof(ReldexFormatOptions)`.
   */
  uint32_t struct_size;
  /**
   * The decimal separator, as a Unicode scalar. `0` means `.`.
   */
  uint32_t decimal_separator;
  /**
   * The digit-group separator, as a Unicode scalar. `0` means no grouping.
   */
  uint32_t grouping_separator;
  /**
   * How many digits per group. `0` means 3 when grouping is on.
   */
  uint32_t grouping_size;
  /**
   * A [`ReldexTimestampStyle`].
   */
  int32_t timestamp_style;
  /**
   * A [`ReldexBytesStyle`].
   */
  int32_t bytes_style;
  /**
   * How many fraction digits to show. Negative means "as stored"; `0`
   * means "as stored" too, since a caller that zeroes the struct is asking
   * for defaults, not for integers.
   */
  int32_t max_fraction_digits;
  /**
   * How many bytes of a `RAW` column to render before eliding the rest.
   * `0` means 32.
   */
  uint32_t max_bytes_rendered;
  /**
   * What to write for SQL NULL. Empty means the empty string — which is why
   * a grid must also *visualize* NULL rather than relying on the text
   * (`SPEC.md` §24: NULL, taken and empty are three different states).
   */
  struct ReldexStr null_text;
  /**
   * What to write for a cell whose large object was taken out of the batch.
   * Empty means `[LOB]`.
   */
  struct ReldexStr taken_text;
} ReldexFormatOptions;

/**
 * Called when the hub's event queue goes from empty to non-empty.
 *
 * Edge-triggered and coalesced: a burst of completions produces **one** call.
 * It must not block and must not call back into `reldex_*` (ADR-0003 D5); any
 * FFI entry from inside it returns `RELDEX_STATUS_REENTRANT` rather than
 * deadlocking. The C++ trampoline should do exactly one thing:
 * `QMetaObject::invokeMethod(bridge, &Bridge::drain, Qt::QueuedConnection)`.
 *
 * It is called from a Reldex thread, never from the caller's.
 */
typedef void (*ReldexWakeFn)(void *user_data);

/**
 * One reply, filled in by [`crate::reldex_hub_next_event`].
 *
 * The caller sets `struct_size` before each call
 * (`ReldexEvent ev = { .struct_size = sizeof ev };`) and **owns** `error` and
 * `batch` when they come back non-null: release them with
 * [`crate::reldex_error_free`] and [`crate::reldex_batch_release`].
 */
typedef struct ReldexEvent {
  /**
   * `sizeof(ReldexEvent)` on the way in; how much of it is valid on the way
   * out.
   */
  uint32_t struct_size;
  /**
   * A [`ReldexEventKind`].
   */
  int32_t kind;
  /**
   * The session this reply belongs to.
   */
  uint64_t session;
  /**
   * The `request_id` the caller passed to the submitting call.
   */
  uint64_t request;
  /**
   * `Executed`: the result set's id, when `has_result`.
   */
  uint64_t result;
  /**
   * `Executed`: rows changed, when `has_rows_affected`.
   */
  uint64_t rows_affected;
  /**
   * `Opened`: the driver connection's id.
   */
  uint64_t connection_id;
  /**
   * `Fetched`: the batch's row count, mirrored here so a caller that only
   * needs "is the result exhausted?" does not have to touch the batch. Zero
   * means exhausted.
   */
  size_t row_count;
  /**
   * The failure, or null on success. The caller owns it.
   */
  struct ReldexError *error;
  /**
   * `Fetched`: the batch, or null. The caller owns it.
   */
  struct ReldexBatch *batch;
  /**
   * The session's lifecycle as of this event: a [`ReldexSessionState`].
   */
  int32_t session_state;
  /**
   * `Executed`: a [`ReldexStatementKind`].
   */
  int32_t statement_kind;
  /**
   * `Opened`: a [`crate::ReldexCancelKind`] — what a cancel on this session
   * can actually do (`SPEC.md` §24.8).
   */
  int32_t cancel_kind;
  /**
   * `SessionClosed`: a [`ReldexCloseOutcome`].
   */
  int32_t close_outcome;
  /**
   * `Executed`: how many columns the result has; read their names with
   * `reldex_batch_column_info` on any batch from it.
   */
  uint32_t column_count;
  /**
   * `Opened`: how many connect-time warnings the session reported. Read
   * them with [`crate::reldex_session_connect_warnings`].
   */
  uint32_t warning_count;
  /**
   * `Executed`: whether the statement produced a result set.
   */
  bool has_result;
  /**
   * `Executed`: whether `rows_affected` is meaningful.
   */
  bool has_rows_affected;
  /**
   * `Executed`: whether the server committed the transaction as a side
   * effect, whatever the client asked for (typically DDL). Reldex could
   * neither prevent nor undo it; the user must be told.
   */
  bool committed_implicitly;
  /**
   * `SessionClosed`: whether the session is still open and usable.
   */
  bool session_still_open;
} ReldexEvent;

/**
 * Identifies one session for this hub's lifetime. Never reused.
 */
typedef uint64_t ReldexSessionId;

/**
 * How a mock session's scripted world is parameterised.
 *
 * Every field is optional in the ADR-0003 D7 sense: a zero means "the
 * default", so a caller may zero the struct, set `struct_size`, and get a
 * usable world.
 */
typedef struct ReldexMockScenarioConfig {
  /**
   * `sizeof(ReldexMockScenarioConfig)`.
   */
  uint32_t struct_size;
  /**
   * A [`ReldexMockScenario`]; `0` selects [`ReldexMockScenario::S14`].
   */
  int32_t scenario;
  /**
   * How many rows [`ReldexMockStatement::GeneratedQuery`] produces.
   * `0` means 1,000.
   */
  uint64_t rows;
  /**
   * Mixed into the generated values; `0` is a valid seed.
   */
  uint64_t seed;
  /**
   * Simulated per-fetch round-trip cost, in microseconds. `0` means none.
   */
  uint64_t per_fetch_latency_us;
  /**
   * Extra simulated cost before the *first* batch, in microseconds.
   * `0` means none.
   */
  uint64_t first_batch_latency_us;
  /**
   * How long [`ReldexMockStatement::Block`] blocks, in milliseconds.
   * `0` means "until [`reldex_mock_release_block`] or a cancel", which is
   * what a deterministic test wants.
   */
  uint64_t block_duration_ms;
} ReldexMockScenarioConfig;

/**
 * How a session is opened.
 */
typedef struct ReldexOpenOptions {
  /**
   * `sizeof(ReldexOpenOptions)`.
   */
  uint32_t struct_size;
  /**
   * A [`crate::ReldexDriverKind`]. This build accepts only
   * `RELDEX_DRIVER_KIND_MOCK`.
   */
  int32_t driver;
  /**
   * The scripted world, when `driver` is the mock.
   */
  struct ReldexMockScenarioConfig mock;
} ReldexOpenOptions;

/**
 * The caller's own correlation id, opaque to Reldex and echoed back on the
 * one event that replies to the request it was passed to.
 */
typedef uint64_t ReldexRequestId;

/**
 * Identifies one open result set, scoped to the session that produced it.
 *
 * An id from another session is simply not found there, so a mixed-up id is
 * *reported* rather than being undefined behaviour (ADR-0003 D3).
 */
typedef uint64_t ReldexResultId;

/**
 * An exact decimal, mirroring `db-driver-api`'s `Number` field for field.
 *
 * The value is `±0.d₁…dₙ × 10^exponent`, with `digits[0..digit_count]` holding
 * digit *values* `0..=9`, most significant first. 40 significant digits, per
 * ADR-0002 amendment S6.
 *
 * Deliberately **without** a `struct_size`: it is an array element, and its
 * size is reported once in [`ReldexColumnView::fixed_stride`]. Compare that
 * against `sizeof(ReldexNumber)` — a mismatch means the header and the
 * library disagree, which is exactly what `struct_size` would have caught.
 */
typedef struct ReldexNumber {
  /**
   * Significant digits, most significant first. Positions at or past
   * `digit_count` are zero.
   */
  uint8_t digits[RELDEX_NUMBER_MAX_DIGITS];
  /**
   * How many of `digits` are significant. Zero means the value is zero.
   */
  uint8_t digit_count;
  /**
   * The decimal exponent.
   */
  int16_t exponent;
  /**
   * Whether the value is negative.
   */
  bool negative;
} ReldexNumber;

/**
 * A date or timestamp, mirroring `db-driver-api`'s `Timestamp`.
 *
 * Without a `struct_size`, for the same reason as [`ReldexNumber`].
 */
typedef struct ReldexTimestamp {
  /**
   * Nanoseconds within the second.
   */
  uint32_t nanosecond;
  /**
   * Proleptic year; negative years are BC in astronomical numbering.
   */
  int16_t year;
  /**
   * Minutes east of UTC, when `has_zone`.
   */
  int16_t zone_offset_minutes;
  /**
   * 1-12.
   */
  uint8_t month;
  /**
   * 1-31.
   */
  uint8_t day;
  /**
   * 0-23.
   */
  uint8_t hour;
  /**
   * 0-59.
   */
  uint8_t minute;
  /**
   * 0-59.
   */
  uint8_t second;
  /**
   * Whether `zone_offset_minutes` is meaningful. A `DATE` has no zone.
   */
  bool has_zone;
} ReldexTimestamp;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version this library implements: `(major << 16) | minor`.
 *
 * Compare against `RELDEX_ABI_VERSION` in `reldex.h`. Its real value is
 * catching a stale header in a developer's build, not distribution: core and
 * UI ship in one binary (ADR-0003 D7).
 */
uint32_t reldex_abi_version(void);

/**
 * How many rows the batch holds. Zero means the result is exhausted.
 *
 * # Safety
 *
 * `batch` must be null (reported as 0) or a live batch.
 */
size_t reldex_batch_row_count(const struct ReldexBatch *batch);

/**
 * How many columns the batch holds.
 *
 * # Safety
 *
 * `batch` must be null (reported as 0) or a live batch.
 */
size_t reldex_batch_column_count(const struct ReldexBatch *batch);

/**
 * Describes column `column`: its name, declared type and storage kind.
 *
 * The strings borrow from the batch.
 *
 * # Safety
 *
 * `batch` must be a live batch and `out` a writable [`ReldexColumnInfo`] with
 * `struct_size` set.
 */
ReldexStatus reldex_batch_column_info(const struct ReldexBatch *batch,
                                      size_t column,
                                      struct ReldexColumnInfo *out);

/**
 * Hands out column `column`'s memory: one call per column per batch, then
 * pointer arithmetic per cell.
 *
 * Every pointer in `out` borrows from `batch` and is valid until
 * [`reldex_batch_release`]. Read a cell by consulting `null_bits` first, then
 * `offsets`/`data` or `fixed` according to `kind`.
 *
 * # Safety
 *
 * `batch` must be a live batch and `out` a writable [`ReldexColumnView`] with
 * `struct_size` set. The returned pointers must not be used after the batch
 * is released.
 */
ReldexStatus reldex_batch_column(const struct ReldexBatch *batch,
                                 size_t column,
                                 struct ReldexColumnView *out);

/**
 * Releases a batch and every pointer taken from it.
 *
 * A null pointer is a no-op. Releasing twice is undefined behaviour, like
 * every `free`. The adapter must release every batch it takes from an event;
 * a batch still sitting in the queue when the hub is destroyed is released
 * for it.
 *
 * # Safety
 *
 * `batch` must be null, or a pointer from a fetched event that has not been
 * released.
 */
void reldex_batch_release(struct ReldexBatch *batch);

/**
 * Takes the last failure recorded **on this thread**, transferring ownership.
 *
 * Returns `NULL` when there is none. Release the result with
 * [`reldex_error_free`]. Calling this twice returns `NULL` the second time:
 * the error exists once.
 */
struct ReldexError *reldex_last_error_take(void);

/**
 * Discards the last failure recorded on this thread, if any.
 */
void reldex_last_error_clear(void);

/**
 * Describes `error` into `out`.
 *
 * # Safety
 *
 * `error` must be a live pointer this library produced and has not yet been
 * freed. `out` must be non-null, aligned, and have its `struct_size` set to
 * the size of the caller's [`ReldexErrorView`].
 */
ReldexStatus reldex_error_view(const struct ReldexError *error, struct ReldexErrorView *out);

/**
 * Releases an error the caller was handed.
 *
 * A null pointer is a no-op. Passing the same pointer twice is undefined
 * behaviour — like every `free`.
 *
 * # Safety
 *
 * `error` must be null, or a pointer this library produced and that has not
 * been freed.
 */
void reldex_error_free(struct ReldexError *error);

/**
 * Creates an arena. Returns `NULL` only if allocation failed.
 */
struct ReldexTextArena *reldex_text_arena_create(void);

/**
 * Releases an arena and every pointer taken from it. A null pointer is a
 * no-op.
 *
 * # Safety
 *
 * `arena` must be null, or a pointer [`reldex_text_arena_create`] returned
 * that has not been released.
 */
void reldex_text_arena_release(struct ReldexTextArena *arena);

/**
 * Empties an arena, keeping its allocation for the next window.
 *
 * # Safety
 *
 * `arena` must be a live arena.
 */
void reldex_text_arena_clear(struct ReldexTextArena *arena);

/**
 * How many strings an arena holds.
 *
 * # Safety
 *
 * `arena` must be null (reported as 0) or a live arena.
 */
size_t reldex_text_arena_count(const struct ReldexTextArena *arena);

/**
 * Describes an arena's buffer and offsets.
 *
 * # Safety
 *
 * `arena` must be a live arena and `out` a writable [`ReldexArenaView`] with
 * `struct_size` set.
 */
ReldexStatus reldex_text_arena_view(const struct ReldexTextArena *arena,
                                    struct ReldexArenaView *out);

/**
 * Formats `row_count` rows of one column into `arena`, appending one string
 * per row.
 *
 * This is the *bulk* formatter ADR-0003 D4 asks for: one call per visible
 * window, never one per cell. A row past the end of the batch is skipped, so
 * the arena holds as many strings as rows actually existed — read
 * [`reldex_text_arena_count`] rather than assuming `row_count`.
 *
 * NULL renders as `options->null_text` and a taken large object as
 * `options->taken_text`; a grid must still *visualize* the difference rather
 * than rely on the text.
 *
 * # Safety
 *
 * `batch` must be a live batch, `arena` a live arena, and `options` null (for
 * the defaults) or a [`ReldexFormatOptions`] with `struct_size` set and any
 * strings in it readable for the duration of the call.
 */
ReldexStatus reldex_batch_format_column(const struct ReldexBatch *batch,
                                        size_t column,
                                        size_t row_start,
                                        size_t row_count,
                                        const struct ReldexFormatOptions *options,
                                        struct ReldexTextArena *arena);

/**
 * Creates the hub. Returns `NULL` only if allocation failed.
 *
 * One per application is the intended shape; nothing here forbids more.
 */
struct ReldexHub *reldex_hub_create(void);

/**
 * Destroys the hub, after every batch and error it handed out has been
 * released.
 *
 * Returns **promptly**, even when a session is blocked inside a statement
 * that cannot be interrupted. In order: the waker is unregistered (which
 * waits for any wake already in flight, D5 rule 2), every session is marked
 * closed and asked to cancel whatever it is running, and the hub's own
 * reference is dropped. A session thread still finishing keeps the hub alive
 * a moment longer and then releases it; events queued in the meantime are
 * freed unread, along with any batch they carry.
 *
 * Like dropping a `DatabaseSession`, this **never commits**: a transaction
 * still open when the hub is destroyed is rolled back by the server, exactly
 * as if the connection had died (`SPEC.md` §10).
 *
 * # Safety
 *
 * `hub` must be null, or a pointer [`reldex_hub_create`] returned that has
 * not already been destroyed. No other thread may be inside a `reldex_*` call
 * on this hub.
 */
void reldex_hub_destroy(struct ReldexHub *hub);

/**
 * Registers (or, with a null `fn`, unregisters) the wake callback.
 *
 * Unregistering does not return while a wake is in progress, so the adapter
 * can destroy the object `user_data` points at immediately afterwards
 * (ADR-0003 D5 rule 2; spike criterion K5).
 *
 * # Safety
 *
 * `hub` must be a live hub. `user_data` is opaque to this library and is only
 * ever passed back to `fn`; it must stay valid until this function is called
 * again with a different (or null) `fn` and returns.
 */
ReldexStatus reldex_hub_set_waker(struct ReldexHub *hub, ReldexWakeFn func, void *user_data);

/**
 * How many events are waiting to be taken. Never blocks.
 *
 * Diagnostics and drain budgeting: the adapter's `drain()` stops at a budget
 * and re-posts (ADR-0003 D5), and this is how it can report, or log, a
 * backlog it is deliberately leaving behind. It is a snapshot — a worker may
 * push another event before the caller acts on it.
 *
 * # Safety
 *
 * `hub` must be null (reported as 0) or a live hub.
 */
size_t reldex_hub_pending_events(const struct ReldexHub *hub);

/**
 * Takes the next event, or reports that there is none. Never blocks.
 *
 * Returns `true` when `out` was filled. The caller then **owns** `out->error`
 * and `out->batch` when they are non-null. Drain in a loop until this returns
 * `false`, budgeting the loop so a flood cannot starve rendering (ADR-0003 D5
 * suggests 256 events / 4 ms, then re-post).
 *
 * Returns `false` if `out` is null, unaligned, or its `struct_size` is too
 * small — the event is **not** consumed in that case, so a mis-sized struct
 * cannot silently lose a batch.
 *
 * # Safety
 *
 * `hub` must be a live hub, and `out` must point at a writable
 * [`ReldexEvent`] whose `struct_size` the caller has initialized.
 */
bool reldex_hub_next_event(struct ReldexHub *hub, struct ReldexEvent *out);

/**
 * The SQL text for one of the scenario's statements, as a borrowed `'static`
 * string. NUL-terminated, so a C caller may use it directly.
 *
 * An unknown kind reports the empty string.
 */
struct ReldexStr reldex_mock_statement(int32_t kind);

/**
 * Releases a session's blocked statement, if the mock world it runs in has
 * one parked.
 *
 * Mock-only, and the reason [`ReldexMockScenarioConfig::block_duration_ms`]
 * may be zero: a test (or spike S15's "a blocked session must not stall the
 * UI" step) blocks a session indefinitely and releases it at a moment of its
 * choosing, with no sleep anywhere. Idempotent, and safe whether or not
 * anything is currently blocked.
 *
 * # Safety
 *
 * `hub` must be a live hub.
 */
ReldexStatus reldex_mock_release_block(struct ReldexHub *hub, ReldexSessionId session);

/**
 * Opens a session and reports its id immediately; the connection itself is
 * made on the session's own thread.
 *
 * This **never blocks**: `db-core`'s `open_session` waits for the connect to
 * finish, so the wait happens on the session's pump thread and the answer
 * arrives as a `RELDEX_EVENT_KIND_OPENED` event carrying `request`. On
 * failure that same request id comes back as an `OPENED` event with a
 * non-null `error` — exactly one reply either way.
 *
 * The session id is valid as soon as this returns, but nothing may be
 * submitted on it until its `OPENED` event arrives without an error.
 *
 * # Safety
 *
 * `hub` must be a live hub; `options` must be null (for the defaults) or
 * point at a [`ReldexOpenOptions`] with `struct_size` set; `out_session` must
 * be null or point at a writable `uint64_t`.
 */
ReldexStatus reldex_hub_open_session(struct ReldexHub *hub,
                                     const struct ReldexOpenOptions *options,
                                     ReldexRequestId request,
                                     ReldexSessionId *out_session);

/**
 * Submits one statement. The reply is a `RELDEX_EVENT_KIND_EXECUTED` event
 * carrying `request`.
 *
 * `deadline_ms` arms a per-statement time limit; `0` means none, with the
 * consequence `SPEC.md` §10 requires the UI to state — on a driver that
 * cannot interrupt a running call, only disconnecting the worksheet can end
 * it, and that loses its transaction.
 *
 * Binds are not exported yet (M2.11).
 *
 * # Safety
 *
 * `hub` must be a live hub, and `sql` must point at `sql.len` readable bytes.
 */
ReldexStatus reldex_session_execute(struct ReldexHub *hub,
                                    ReldexSessionId session,
                                    ReldexRequestId request,
                                    struct ReldexStr sql,
                                    uint64_t deadline_ms);

/**
 * Submits a fetch of at most `max_rows` more rows of `result`.
 *
 * The reply is a `RELDEX_EVENT_KIND_FETCHED` event carrying `request`; on
 * success it owns a `ReldexBatch*`, and a batch with **no rows** means the
 * result is exhausted.
 *
 * # Safety
 *
 * `hub` must be a live hub.
 */
ReldexStatus reldex_session_fetch(struct ReldexHub *hub,
                                  ReldexSessionId session,
                                  ReldexRequestId request,
                                  ReldexResultId result,
                                  uint32_t max_rows);

/**
 * Releases a result set and every large object taken from it. The reply is a
 * `RELDEX_EVENT_KIND_RESULT_CLOSED` event carrying `request`.
 *
 * # Safety
 *
 * `hub` must be a live hub.
 */
ReldexStatus reldex_session_close_result(struct ReldexHub *hub,
                                         ReldexSessionId session,
                                         ReldexRequestId request,
                                         ReldexResultId result);

/**
 * Closes a session, resolving its transaction first.
 *
 * The reply is a `RELDEX_EVENT_KIND_SESSION_CLOSED` event carrying `request`.
 * Read its `close_outcome`: `DECISION_REQUIRED`, `COMMIT_FAILED` and
 * `ROLLBACK_FAILED` all leave the session **open and usable**, so the caller
 * can ask the user and close again. This is the only path that can commit;
 * destroying the hub never does.
 *
 * # Safety
 *
 * `hub` must be a live hub.
 */
ReldexStatus reldex_session_close(struct ReldexHub *hub,
                                  ReldexSessionId session,
                                  ReldexRequestId request,
                                  int32_t disposition);

/**
 * Asks the session's driver to stop whatever it is running.
 *
 * Deliberately callable from **any** thread, unlike every other function
 * here, and it returns promptly: it never goes through the request queue a
 * blocked statement would stall (ADR-0002 D2). It produces no event — the
 * cancelled statement's own reply is where the outcome shows up. Check
 * `RELDEX_EVENT_KIND_OPENED`'s `cancel_kind` first: on a driver that cannot
 * interrupt a running call this reports `NOT_INTERRUPTIBLE`, and the UI must
 * say so rather than show a cancel in progress.
 *
 * # Safety
 *
 * `hub` must be a live hub; `out_outcome` must be null or point at a writable
 * `int32_t`.
 */
ReldexStatus reldex_session_request_cancel(struct ReldexHub *hub,
                                           ReldexSessionId session,
                                           int32_t *out_outcome);

/**
 * Appends this session's connect-time warnings to `arena`, one string per
 * warning, in the order the driver reported them.
 *
 * These are the non-fatal findings from opening the connection — a TLS
 * parameter the driver could not honour, say — and the `OPENED` event's
 * `warning_count` says how many to expect. They are constant for the
 * session's life, so reading them late is not the same as losing them.
 *
 * # Safety
 *
 * `hub` must be a live hub and `arena` a live arena.
 */
ReldexStatus reldex_session_connect_warnings(struct ReldexHub *hub,
                                             ReldexSessionId session,
                                             struct ReldexTextArena *arena);

/**
 * Converts a Unicode **scalar** offset into a UTF-16 code-unit offset.
 *
 * `SqlPosition` counts scalars (ADR-0002 S3); `QString` counts UTF-16 units.
 * Thai is BMP and the two coincide there, but the non-BMP corpus of spike S11
 * proves they do not in general, so the adapter must never guess. An offset
 * past the end of `text` reports the string's full UTF-16 length, which is
 * where a caret belongs when the server points one character past the last.
 *
 * Returns [`RELDEX_UTF16_OFFSET_INVALID`] if `text` is not valid UTF-8 or its
 * pointer is null.
 *
 * # Safety
 *
 * `text` must be a `ReldexStr` this library produced, or point at `len`
 * readable initialized bytes.
 */
size_t reldex_utf16_offset(struct ReldexStr text, size_t char_offset);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

/* The packed version reldex_abi_version() returns, for the check the adapter
 * makes before anything else. A macro rather than a Rust constant because
 * cbindgen does not evaluate expressions. */
#define RELDEX_ABI_VERSION ((((uint32_t)RELDEX_ABI_VERSION_MAJOR) << 16) | ((uint32_t)RELDEX_ABI_VERSION_MINOR))

/* What reldex_utf16_offset() returns when it cannot answer. Mirrors
 * `RELDEX_UTF16_OFFSET_INVALID` in the Rust crate, which is `usize::MAX`. */
#define RELDEX_UTF16_OFFSET_INVALID ((size_t)-1)
